config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'

  resources :users
  resources :projects

  get 'projects/:id/manage_collaborators' => 'projects#manage_collaborators', as: :manage_project_collaborators
  post 'projects/:id/manage_collaborators/find_collaborator' => 'projects#find_collaborator', as: :find_project_collaborator
  get 'projects/:id/manage_collaborators/add_user/:user_id' => 'projects#add_user', as: :add_project_collaborators

  get 'my-projects/' => 'my_projects#index', as: :my_projects
  get 'project/:project_id' => 'my_projects#show_project', as: :show_my_project
  
  scope 'project/:project_id' do
    resources :notes
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  scope :user_projects, -> ( user_id ) { 
    joins(:user_project).where("user_project.user_id = ?" , user_id ) 
  }

  has_many  :user_project

  validates_presence_of :name

  def add_collaborator(user)
    if( UserProject.find_by_project_id_and_user_id( self.id , user.id ).nil? )
      up = UserProject.new
      up.user= user
      up.project=self
      self.user_project.push up
      return
    end
    raise "User already in the project"
  end

  def collaborators
    self.user_project.map{ |up| up.user }
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy,
      :manage_collaborators , :find_collaborator , :add_user]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def manage_collaborators
    @collaborators = @project.collaborators
  end

  def find_collaborator
    @search = params[:search]
    puts "Project #{@project.id}"
    @resultSearch = User.find_users_not_in_the_project @search , @project.id
    manage_collaborators()
    respond_to do |f| f.html { render :manage_collaborators } end
  end

  def add_user
    @project.add_collaborator( User.find_by_id(params[:user_id]))
    manage_collaborators()
    respond_to do |f| f.html { render :manage_collaborators } end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_collaborators.html.erb
<table>
    <thead>
        <tr>
            <th>Nome</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <% @collaborators.each do |c| %>
        <tr>
            <td><%= c.username %></td>
            <td></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3">Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td>
          <%= link_to 'Manage Collaborators', manage_project_collaborators_path(project) %>
          <%= link_to 'Show', project %>
          <%= link_to 'Edit', edit_project_path(project) %>
          <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/manage_collaborators.html.erb
<form method="post" action="<%= find_project_collaborator_path(@project) %>">
    <%= tag(:input , :type => "hidden" , :name => request_forgery_protection_token.to_s,
     :value => form_authenticity_token ) %>
    <div>
        <labeL for="search">Buscar Usuário:</div>
        <input id="search" name="search" value="<%= @search %>" />
        <button type="submit">Buscar</button>
    </div>
</form>

<% if @resultSearch %>
    <h3>Resultado busca</h3>
    <% if @resultSearch.size > 0 %>
        <table>
            <thead>
                <tr>
                    <th>Nome</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <% @resultSearch.each do |c| %>
                <tr>
                    <td><%= c.username %></td>
                    <td><a href="<%= add_project_collaborators_path(@project , c.id)%>">Adicionar ao projeto</a></td>
                </tr>
            <% end %>
            </tbody>
        </table>
    <% else %>
        <p>Nenhum registro encontrado</p>
    <% end %>
<% end %>
<h3>Colaboradores</h3>
<%= render "collaborators" %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>