config/routes.rb
Rails.application.routes.draw do
  

  root 'home#index'

  resources :users
  resources :projects

  get 'projects/:id/manage_collaborators' => 'projects#manage_collaborators', as: :manage_project_collaborators
  post 'projects/:id/manage_collaborators/find_collaborator' => 'projects#find_collaborator', as: :find_project_collaborator
  get 'projects/:id/manage_collaborators/add_user/:user_id' => 'projects#add_user', as: :add_project_collaborators

  get 'my-projects/' => 'my_projects#index', as: :my_projects
  get 'project/:project_id' => 'my_projects#show_project', as: :show_my_project
  
  scope 'project/:project_id' do
    resources :notes
  end

end

app/views/layouts/_menu.html.erb
<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li class="sidebar-brand">
            <%= link_to 'DocBay', root_url %></a>
        </li>
        <li><a href="<%= users_path %>">Users</a></li>
        <li><a href="<%= projects_path %>">Projects</a></li>
        <li><a href="<%= my_projects_path %>">My Projects</a></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Docbay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="wrapper">
        <!-- Sidebar -->
        <%= render "layouts/menu" %>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
</body>
</html>

app/views/layouts/project.html.erb
<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
  <title>Docbay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">
    <!-- Sidebar -->
    <%= render "layouts/menu" %>
    <!-- /#sidebar-wrapper -->
    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <h1><%= @project.name %></h1>
                    
                    <ul>
                        <li><%= link_to "Notas", notes_path %></li>
                    </ul>
                        
                    <%= yield %>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->
    </div>
<div>

</body>
</html>